const products=[
 {id:'no01',name:'AUREL No. 01',subtitle:'Automatic',price:1290,image:'assets/images/watch-no01.png',position:'50%',description:'The founding AUREL: a study in proportion, legibility and quiet detail, made for every part of the day.',specs:{Case:'39mm stainless steel',Movement:'Automatic movement',Crystal:'Sapphire crystal',Water:'100m resistance'},straps:['Black Leather','Brown Leather','Steel Bracelet']},
 {id:'midnight',name:'AUREL Midnight',subtitle:'Automatic',price:1490,image:'assets/images/watch-midnight.png',position:'50%',description:'A deeper expression of the essential watch, with low-light tones and sharply considered details.',specs:{Case:'39mm coated steel',Movement:'Automatic movement',Crystal:'Sapphire crystal',Water:'100m resistance'},straps:['Black Leather','Charcoal Textile','Steel Bracelet']},
 {id:'chrono',name:'AUREL Chronograph',subtitle:'Automatic Chronograph',price:1690,image:'assets/images/watch-chronograph.png',position:'50%',description:'Measured performance in a balanced silhouette, designed to feel composed rather than complicated.',specs:{Case:'41mm stainless steel',Movement:'Automatic chronograph',Crystal:'Sapphire crystal',Water:'100m resistance'},straps:['Brown Leather','Black Leather','Steel Bracelet']},
 {id:'field',name:'AUREL Field',subtitle:'Automatic',price:1190,image:'assets/images/watch-field.png',position:'50%',description:'Clear, capable and made for movement. A purposeful everyday watch with an understated character.',specs:{Case:'38mm stainless steel',Movement:'Automatic movement',Crystal:'Sapphire crystal',Water:'100m resistance'},straps:['Olive Textile','Brown Leather','Steel Bracelet']}
];
const $=(s,c=document)=>c.querySelector(s),$$=(s,c=document)=>[...c.querySelectorAll(s)],money=n=>new Intl.NumberFormat('en-IE',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(n);
let cart=[];try{cart=JSON.parse(localStorage.getItem('aurel-cart'))||[]}catch{}let activeProduct=null,selectedStrap='',lastFocus=null;
const grid=$('#product-grid');grid.innerHTML=products.map((p,i)=>`<article class="product-card reveal"><div class="product-image"><img src="${p.image}" alt="${p.name}, ${p.subtitle.toLowerCase()} watch" style="object-position:${p.position}" loading="lazy"><button class="quick-btn" data-quick="${p.id}" aria-label="Quick view ${p.name}">Quick view</button></div><div class="product-meta"><div><h3>${p.name}</h3><p>${p.subtitle}</p></div><strong>${money(p.price)}</strong></div></article>`).join('');
const overlay=$('.overlay'),modal=$('.modal'),drawer=$('.cart-drawer'),searchPanel=$('.search-panel');
function trapFocus(e,container){if(e.key!=='Tab')return;const f=$$('button,[href],input,[tabindex]:not([tabindex="-1"])',container).filter(x=>!x.disabled);if(!f.length)return;const first=f[0],last=f.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}
function showLayer(el){lastFocus=document.activeElement;overlay.hidden=false;requestAnimationFrame(()=>el.classList.add('open'));el.setAttribute('aria-hidden','false');document.body.classList.add('lock');setTimeout(()=>($('button,input',el)||el).focus(),50)}
function closeLayers(){[modal,drawer,searchPanel].forEach(x=>{x.classList.remove('open');x.setAttribute('aria-hidden','true')});overlay.hidden=true;document.body.classList.remove('lock');if(lastFocus)lastFocus.focus()}
function openModal(id){activeProduct=products.find(p=>p.id===id);selectedStrap=activeProduct.straps[0];$('.modal-image img').src=activeProduct.image;$('.modal-image img').alt=`${activeProduct.name} product view`;$('.modal-image img').style=`object-position:${activeProduct.position}`;$('.modal-subtitle').textContent=activeProduct.subtitle;$('#modal-title').textContent=activeProduct.name;$('.modal-price').textContent=money(activeProduct.price);$('.modal-description').textContent=activeProduct.description;$('.modal-specs').innerHTML=Object.entries(activeProduct.specs).map(([k,v])=>`<div><dt>${k}</dt><dd>${v}</dd></div>`).join('');$('.strap-options').innerHTML=activeProduct.straps.map((s,i)=>`<button class="strap-option ${i?'':'selected'}" data-strap="${s}" aria-pressed="${!i}">${s}</button>`).join('');showLayer(modal)}
document.addEventListener('click',e=>{const q=e.target.closest('[data-quick]');if(q)openModal(q.dataset.quick);const st=e.target.closest('[data-strap]');if(st){selectedStrap=st.dataset.strap;$$('.strap-option').forEach(x=>{x.classList.toggle('selected',x===st);x.setAttribute('aria-pressed',x===st)})}});
$('.modal-add').addEventListener('click',()=>{const found=cart.find(i=>i.id===activeProduct.id&&i.strap===selectedStrap);found?found.quantity++:cart.push({id:activeProduct.id,strap:selectedStrap,quantity:1});saveCart();closeLayers();openCart()});
function saveCart(){localStorage.setItem('aurel-cart',JSON.stringify(cart));renderCart()}
function renderCart(){const count=cart.reduce((a,i)=>a+i.quantity,0);$('.bag-count').textContent=count;$('.bag-count').setAttribute('aria-label',`${count} items`);$('.cart-heading-count').textContent=`(${count})`;const box=$('.cart-items');box.innerHTML=cart.length?cart.map((i,n)=>{const p=products.find(x=>x.id===i.id);return `<article class="cart-item"><img src="${p.image}" alt="${p.name}" style="object-position:${p.position}"><div><div class="cart-item-head"><div><h3>${p.name}</h3><p>${i.strap}</p></div><strong>${money(p.price*i.quantity)}</strong></div><div class="qty" aria-label="Quantity"><button data-cart="minus" data-index="${n}" aria-label="Decrease ${p.name} quantity">−</button><span>${i.quantity}</span><button data-cart="plus" data-index="${n}" aria-label="Increase ${p.name} quantity">+</button></div><button class="remove-item" data-cart="remove" data-index="${n}">Remove</button></div></article>`}).join(''):'<p class="empty-cart">Your bag is currently empty.</p>';$('.cart-total').textContent=money(cart.reduce((sum,i)=>sum+(products.find(p=>p.id===i.id)?.price||0)*i.quantity,0))}
function openCart(){renderCart();showLayer(drawer)}$('.bag-btn').addEventListener('click',openCart);$('.cart-items').addEventListener('click',e=>{const b=e.target.closest('[data-cart]');if(!b)return;const n=+b.dataset.index;if(b.dataset.cart==='plus')cart[n].quantity++;if(b.dataset.cart==='minus')cart[n].quantity--;if(b.dataset.cart==='remove'||cart[n]?.quantity<1)cart.splice(n,1);saveCart()});
$('.checkout-btn').addEventListener('click',()=>{$('.checkout-message').textContent=cart.length?'Demo checkout — no real purchase will be processed.':'Add a watch to your bag to continue.'});
$('.close-modal').onclick=$('.close-cart').onclick=$('.close-search').onclick=closeLayers;overlay.onclick=closeLayers;
$('.search-btn').addEventListener('click',()=>showLayer(searchPanel));$('#search-input').addEventListener('input',e=>{const term=e.target.value.trim().toLowerCase();const p=products.find(x=>x.name.toLowerCase().includes(term));$('.search-panel p').textContent=p?`${p.name} — ${money(p.price)}`:'Try “Midnight” or “Field”.'});
const menuBtn=$('.menu-btn'),mobileMenu=$('.mobile-menu');function closeMenu(){mobileMenu.classList.remove('open');mobileMenu.setAttribute('aria-hidden','true');menuBtn.setAttribute('aria-expanded','false');document.body.classList.remove('lock')}menuBtn.addEventListener('click',()=>{const open=!mobileMenu.classList.contains('open');mobileMenu.classList.toggle('open',open);mobileMenu.setAttribute('aria-hidden',!open);menuBtn.setAttribute('aria-expanded',open);document.body.classList.toggle('lock',open)});$$('.mobile-menu a').forEach(a=>a.onclick=closeMenu);
document.addEventListener('keydown',e=>{if(e.key==='Escape'){if(mobileMenu.classList.contains('open'))closeMenu();else closeLayers()}if(modal.classList.contains('open'))trapFocus(e,modal);if(drawer.classList.contains('open'))trapFocus(e,drawer);if(searchPanel.classList.contains('open'))trapFocus(e,searchPanel)});
$('#newsletter-form').addEventListener('submit',e=>{e.preventDefault();const input=$('#email'),msg=$('.form-message'),valid=/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(input.value.trim());msg.classList.toggle('error',!valid);msg.textContent=valid?'Thank you for joining AUREL.':'Please enter a valid email address.';if(valid){input.value='';input.disabled=true}});
const observer=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:.12});$$('.reveal').forEach(el=>observer.observe(el));
addEventListener('scroll',()=>$('#header').classList.toggle('scrolled',scrollY>30),{passive:true});$('#year').textContent=new Date().getFullYear();renderCart();
